
<!doctype html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            
                Začátečnický kurz v Tieto Czech: Exceptions
            
        </title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        

        <link rel="stylesheet" href="/static/css/naucse.css">
        <link rel="stylesheet" href="/static/css/body.css">
        <link rel="stylesheet" href="/static/css/pygments-lovelace-style.css">
        <link rel="stylesheet" href="/static/css/ipython.css">

        
    


        <style>
            
    

        </style>
    </head>

    <body>
        <nav class="header">
            <ul class="container menu">
                <li><a href="/" class="logo"><h1>Nauč se Python!</h1></a></li>
                <li><a href="/courses/" class="menu-link"><h2>Materiály</h2></a></li>
                <li><a href="/runs/" class="menu-link"><h2>Kurzy</h2></a></li>
            </ul>
        </nav>

        

<div class="page">
    <div class="container">

        
            <header class="lesson-header">
                <a href="/">Nauč se Python </a>
                
                > <a href="/runs/">Kurzy</a>
                
                

> <a href="/2018/tieto/">Začátečnický kurz v Tieto Czech</a>

> <a href="/2018/tieto/sessions/files-and-exceptions/">Soubory a výjimky</a>

> <a href="/2018/tieto/beginners/tieto-exceptions/">Exceptions</a>


                <hr>
            </header>
        

        
  


        <div class="lesson-content">
          
    

    <h2>Exceptions</h2>
<p>An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions. In general, when a Python script encounters a situation that it cannot cope with, it raises an exception. An exception is a Python object that represents an error.</p>
<p>When a Python script raises an exception, it must either handle the exception immediately otherwise it terminates and quits.</p>
<div class="highlight"><pre><code>&gt;&gt;&gt; 1 / 0
Traceback (most recent call last):
   File "&lt;stdin&gt;", line 1, in ?
ZeroDivisionError: integer division or modulo by zero</code></pre></div><h3>raise statement</h3>
<p>You can raise exceptions in several ways by using the raise statement. An exception can be a string, a class or an object. Most of the exceptions that the Python core raises are classes, with an argument that is an instance of the class.</p>
<div class="highlight"><pre><code>&gt;&gt;&gt; raise Exception
Traceback (most recent call last):
   File "&lt;stdin&gt;", line 1, in ?
Exception
&gt;&gt;&gt; raise Exception('hyperdrive overload')
Traceback (most recent call last):
   File "&lt;stdin&gt;", line 1, in ?
Exception: hyperdrive overload</code></pre></div><p>Build-in Exceptions:</p>
<table>
<thead><tr>
<th>Class Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>Exception</td>
<td>The base class for almost all exceptions.</td>
</tr>
<tr>
<td>AttributeError</td>
<td>Raised when attribute reference or assignment fails.</td>
</tr>
<tr>
<td>OSError</td>
<td>Raised when the operating system can’t perform a task, such as a file, for example. Has several specific subclasses.</td>
</tr>
<tr>
<td>IndexError</td>
<td>Raised when using a nonexistent index on a sequence. Subclass of LookupError.</td>
</tr>
<tr>
<td>KeyError</td>
<td>Raised when using a nonexistent key on a mapping. Subclass of LookupError.</td>
</tr>
<tr>
<td>NameError</td>
<td>Raised when a name (variable) is not found.</td>
</tr>
<tr>
<td>SyntaxError</td>
<td>Raised when the code is ill-formed.</td>
</tr>
<tr>
<td>TypeError</td>
<td>Raised when a built-in operation or function is applied to an object of the wrong type.</td>
</tr>
<tr>
<td>ValueError</td>
<td>Raised when a built-in operation or function is applied to an object with the correct type but with an inappropriate value.</td>
</tr>
<tr>
<td>ZeroDivisionError</td>
<td>Raised when the second argument of a division or modulo operation is zero.</td>
</tr>
</tbody>
</table>
<h3>Create custom exception class</h3>
<div class="highlight"><pre><code>class SomeCustomException(Exception): pass</code></pre></div><h3>Catching exceptions</h3>
<div class="highlight"><pre><code>try:
    x = int(input('Enter the first number: '))
    y = int(input('Enter the second number: '))
    print(x / y)
except ZeroDivisionError:
    print("The second number can't be zero!")</code></pre></div><p><strong>More than one except clause</strong></p>
<div class="highlight"><pre><code>try:
   x = int(input('Enter the first number: '))
   y = int(input('Enter the second number: '))
   print(x / y)
except ZeroDivisionError:
   print("The second number can't be zero!")
except TypeError:
   print("That wasn't a number, was it?")</code></pre></div><p><strong>Two exceptions with one block</strong></p>
<div class="highlight"><pre><code>try:
   x = int(input('Enter the first number: '))
   y = int(input('Enter the second number: '))
   print(x / y)
except (ZeroDivisionError, TypeError, NameError):
   print('Your numbers were bogus ...')</code></pre></div><p><strong>Printing error</strong></p>
<div class="highlight"><pre><code>try:
    x = int(input('Enter the first number: '))
    y = int(input('Enter the second number: '))
    print(x / y)
except (ZeroDivisionError, TypeError) as e:
    print(e)</code></pre></div><p><strong>Catching all</strong></p>
<div class="highlight"><pre><code>try:
    x = int(input('Enter the first number: '))
    y = int(input('Enter the second number: '))
    print(x / y)
except:
    print('Something wrong happened ...')</code></pre></div><p><strong>Catching all, done right</strong></p>
<div class="highlight"><pre><code>try:
    x = int(input('Enter the first number: '))
    y = int(input('Enter the second number: '))
    print(x / y)
except Exception as e:
    print('Something wrong happened: %s' % (e,))</code></pre></div><p><strong>Using else clause</strong></p>
<div class="highlight"><pre><code>try:
   print('A simple task')
except:
   print('What? Something went wrong?')
else:
   print('Ah ... It went as planned.')</code></pre></div><p><strong>Using finally clause</strong></p>
<div class="highlight"><pre><code>x = None
try:
    x = 1 / 0
finally:
    print('Cleaning up ...')
    del x</code></pre></div><p><strong>Combine it all</strong></p>
<div class="highlight"><pre><code>try:
    1 / 0
except NameError:
    print("Unknown variable")
else:
    print("That went well!")
finally:
    print("Cleaning up.")</code></pre></div>


        </div>

        
        <hr class="lesson-end">

        
            <div class="alert alert-info">
                Toto je stránka lekce z kurzu, který probíhá nebo proběhl naživo s instruktorem.
                
            </div>
        


        
    <div class="row prev-next">
        
            
                
    <div class="col text-left">
        <a href="/2018/tieto/beginners/tieto-files/">← <span class="d-none d-sm-inline">Files</span></a>
    </div>

            
            
                
    <div class="col text-left">
        <a href="/2018/tieto/sessions/files-and-exceptions/">↑ <span class="d-none d-sm-inline">Lekce: Soubory a výjimky</span></a>
    </div>

            
            
                
    <div class="col text-right">
        <a href="/2018/tieto/sessions/files-and-exceptions/back/"><span class="d-none d-sm-inline">Závěr lekce</span> →</a>
    </div>

            
        
    </div>


        

    </div>
</div>



        <script type="text/javascript" src="/static/js/solutions.js"></script>

        <div class="footer container">
            <hr>
            <div class="lesson-attribution">
                
                    <p>
                        Uprav tuto stránku na
                        <a href="https://github.com/pyvec/naucse.python.cz/blob/archive/2018-tieto/lessons/beginners/tieto-exceptions/index.md">
                            
                                <svg class="icon icon-github" viewBox="0 0 64 64">
<path d="M32 0 C14 0 0 14 0 32 0 53 19 62 22 62 24 62 24 61 24 60 L24 55 C17 57 14 53 13 50 13 50 13 49 11 47 10 46 6 44 10 44 13 44 15 48 15 48 18 52 22 51 24 50 24 48 26 46 26 46 18 45 12 42 12 31 12 27 13 24 15 22 15 22 13 18 15 13 15 13 20 13 24 17 27 15 37 15 40 17 44 13 49 13 49 13 51 20 49 22 49 22 51 24 52 27 52 31 52 42 45 45 38 46 39 47 40 49 40 52 L40 60 C40 61 40 62 42 62 45 62 64 53 64 32 64 14 50 0 32 0 Z" fill="currentColor" stroke-width="0"/>
</svg>
                            
                          GitHubu
                        </a>
                    </p>
                

                
    
        <p>Pro Tieto Czech s.r.o. napsal Lumír Jasiok, 2018</p>
    

                
    <p>
        Licence:
        <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            Creative Commons Attribution-ShareAlike 4.0 International
        </a>
    </p>
    

                
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

        

    </body>
</html>